---
driver:
  name: vagrant
  require_chef_omnibus: 11.16.4

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[fake::manual]
      - recipe[fake::nodejs]
      - recipe[fake::rails]
      - recipe[fake::scala]
    attributes:
